/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestbiblio.gestbiblio.models;

import Controller.AdherentJpaController;
import Controller.LivreJpaController;
import Controller.exceptions.IllegalOrphanException;
import Controller.exceptions.NonexistentEntityException;
import gestbiblio.gestbiblio.Entité.Adherent;
import gestbiblio.gestbiblio.Entité.Livre;
import java.util.ArrayList;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class AddAdherent extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form AddAdherent
     */
    public AddAdherent() {
       
        initComponents();
                 Refresh();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtsexe = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btAjout = new javax.swing.JButton();
        btAnnuler = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btSupp = new javax.swing.JButton();
        btedit = new javax.swing.JButton();
        txtadresse = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter Adhérent"));

        jLabel19.setText("Nom");

        jLabel20.setText("Prenom");

        jLabel21.setText("Sexe");

        jLabel22.setText("adresse");

        jLabel23.setText("Téléphone");

        jLabel24.setText("Email");

        btAjout.setText("Ajouter");
        btAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjoutActionPerformed(evt);
            }
        });

        btAnnuler.setText("Annuler");
        btAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnulerActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id Adherent", "Nom", "Prénom", "sexe", "adresse", "Téléphone", "Email"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btSupp.setText("Supprimer");
        btSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuppActionPerformed(evt);
            }
        });

        btedit.setText("Modifier");
        btedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btAjout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btedit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSupp)
                .addGap(18, 18, 18)
                .addComponent(btAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21))
                .addGap(59, 59, 59)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtprenom)
                    .addComponent(txtsexe)
                    .addComponent(txtTelephone)
                    .addComponent(txtemail)
                    .addComponent(txtnom)
                    .addComponent(txtadresse, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addComponent(txtsexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtadresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAjout)
                    .addComponent(btAnnuler)
                    .addComponent(btSupp)
                    .addComponent(btedit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjoutActionPerformed
         try {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("GestBiblioPU");
        System.out.println(emf.getProperties());
        AdherentJpaController controler = new AdherentJpaController(emf);
    
       
        if(
                (txtnom.getText().equals(""))
                || 
                (txtprenom.getText().equals(""))
                 ||
                 (txtsexe.getText().equals(""))
                 ||
                 (txtadresse.getText().equals(""))
                 ||
                 (txtTelephone.getText().equals(""))
                 ||
                 (txtemail.getText().equals(""))
           ){
                JOptionPane.showMessageDialog(null,"Veuillez renseigner les champs nom,prenom,sexe,adresse,téléphone,email!","Gestion des Bibliothéque",JOptionPane.WARNING_MESSAGE);
                return;
            }
       
       
        String nom = txtnom.getText();
        String prenom = txtprenom.getText();
        String sexe = txtsexe.getText();
        String adresse = txtadresse.getText();
        int telphone = Integer.parseInt(txtTelephone.getText());
        String email = txtemail.getText();
    
                Adherent adher = new Adherent(sexe,nom,prenom,adresse,telphone,email);
  
            controler.create(adher);
        
                        List<Adherent> AdherList =controler.findAdherentEntities();

            AfficheListeDesAdherent(AdherList);
         
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("erreurrrrrr");
            //Logger.getLogger(AddAdherent.class.getName()).log(Level.SEVERE,null,ex);
        }
         Refresh();
    }//GEN-LAST:event_btAjoutActionPerformed

    private void btAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnulerActionPerformed
        AcceuilAdministrateur frame = new AcceuilAdministrateur ();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btAnnulerActionPerformed
/***/
    private void bteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteditActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory fact = Persistence.createEntityManagerFactory("GestBiblioPU");
        System.out.println(fact.getProperties());
        AdherentJpaController controler = new AdherentJpaController(fact);
           // List<Adherent> adhList =controler.findAdherentEntities();

        List<Adherent> updated_adh = new ArrayList<>();
        for(int i = 0;i<jTable2.getModel().getRowCount();i++){
            int id = Integer.parseInt( String.valueOf( jTable2.getModel().getValueAt(i,0) ) );
            String nom = String.valueOf( jTable2.getModel().getValueAt(i,1) );
            String prenom = String.valueOf( jTable2.getModel().getValueAt(i,2) );
            String sexe = String.valueOf( jTable2.getModel().getValueAt(i,3) );
            String adresse = String.valueOf( jTable2.getModel().getValueAt(i,4) );
            int telphone=Integer.parseInt( String.valueOf( jTable2.getModel().getValueAt(i,5) ));
             String email = String.valueOf( jTable2.getModel().getValueAt(i,6) );

            Adherent adh = new Adherent(id,sexe,nom,prenom,adresse,telphone,email);
            updated_adh.add(adh);
        }

        for(Adherent adh : updated_adh){
            try {
                controler.edit(adh);
            } catch (IllegalOrphanException e) {
                e.printStackTrace();
            } catch (NonexistentEntityException e) {
                e.printStackTrace();
            } catch (Exception e) {
                e.printStackTrace();
            }

                List<Adherent> AdherList =controler.findAdherentEntities();
            AfficheListeDesAdherent(AdherList);
            
        }
Refresh();
    }//GEN-LAST:event_bteditActionPerformed

    private void btSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuppActionPerformed
        // TODO add your handling code here:
        
        EntityManagerFactory fact = Persistence.createEntityManagerFactory("GestBiblioPU");
        System.out.println(fact.getProperties());
        AdherentJpaController controler = new AdherentJpaController(fact);

        int adh_id = Integer.parseInt( String.valueOf( jTable2.getModel().getValueAt(jTable2.getSelectedRow(),0) ) );
        System.out.println("adherent id selected : " +adh_id);
        try {
            controler.destroy(adh_id);
            List<Adherent> AdhList =controler.findAdherentEntities();
            AfficheListeDesAdherent(AdhList);
        } catch (IllegalOrphanException e) {
            e.printStackTrace();
        } catch (NonexistentEntityException e) {
            e.printStackTrace();
        }
        Refresh();
    }//GEN-LAST:event_btSuppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAdherent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAdherent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAdherent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAdherent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAdherent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjout;
    private javax.swing.JButton btAnnuler;
    private javax.swing.JButton btSupp;
    private javax.swing.JButton btedit;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtadresse;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtsexe;
    // End of variables declaration//GEN-END:variables

    private void AfficheListeDesAdherent(List<Adherent> findAdherentEntities) {


            jTable2.removeAll();

            while (model.getRowCount() > 0)
                model.removeRow(0);

            if(model.getColumnCount() == 0){
                model.addColumn("ID");
                model.addColumn("Nom");
                model.addColumn("Prenom");
                model.addColumn("Sexe");
                model.addColumn("Adresse");
                model.addColumn("Telephone");
                model.addColumn("Email");
            }

            for(Adherent A : findAdherentEntities){
                model.addRow(new Object[] { A.getIdAdh(),A.getNom(),A.getPrenom(),A.getSexe(),A.getAdresse(),A.getTelephone(),A.getEmail() });
            }
            jTable2.setModel(model);
    }
     private void Refresh(){
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("GestBiblioPU");
        AdherentJpaController controler = new AdherentJpaController(emf);
        AfficheListeDesAdherent(controler.findAdherentEntities());
    }
}
